name: Notify Slack

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.1.0
        with:
          payload: |
            {
              "text": "${{ github.event_name == 'push' && format('A new push has occurred!\n*Commit message:* {0}', github.event.head_commit.message) || format('A pull request event has occurred!\n*PR title:* {0}', github.event.pull_request.title) }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
