name: Notify Slack

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: Slack
    steps:
      - name: Slack: Send to Slack
        uses: slackapi/slack-github-action@v2.1.0
        with:
          payload: |
            {
              "text": "A new push or pull request event has occurred on the repository!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}